label: Cards
status: wip

variants:
  - name: pink
    label: "Theme: Pink"
  - name: red
    label: "Theme: Red"
  - name: slate
    label: "Theme: Slate"
  - name: maroon
    label: "Theme: Maroon"
  - name: blue-dil
    label: "Theme: Blue (DIL)"

  - name: ksp
    label: "KSP (Key Selling Points)"

  - name: overlap-title
    status: caution