label: Cards
status: ready

variants:
  - name: pink
    label: "Theme: Pink"
  - name: red
    label: "Theme: Red"
  - name: slate
    label: "Theme: Slate"
  - name: maroon
    label: "Theme: Maroon"
  - name: blue-ldn
    label: "Theme: Blue (LDN)"

  - name: ksp
    label: "KSP (Key Selling Points)"
  - name: ksp-light
    label: "KSP (Light on Dark)"