name: Tile
status: not_started
context:
  classes: []
  image: 'masthead.jpg'
  link: '#'
  title: 'This is the tile title'
  date: '24th January 2020'
  content: 'This is the text content of the tile...'
  button: 'Book now'
handle: tile


