name: Slab
status: ready
collated: false
context:
  text: 'This is a slab'
  background: []
  modifiers: []
handle: slab

variants:
  - name: offwhite
    label: "Background: Offwhite"
    context:
      background: offwhite
      text: 'This is an offwhite slab'

  - name: slate
    label: "Background: Slate"
    context:
      background: slate
      text: 'This is a slate slab'

  - name: bg-img
    label: "Background Image"
    context:
      background: img
      text: 'This is a slab with background image'