status: wip
label: 'Sliders'

variants:
  - name: default
    hidden: true
  - name: accolades
    label: "Accolade Slider"
  - name: event-cards
    label: "Event Cards Slider"
  - name: tiles
    label: "Tiles Slider"
  - name: tiles-gallery
    label: "Tiles (Gallery)"
  - name: gallery
    label: "Gallery Slider"