status: wip
context:
  text: 'Click me'
preview: '@preview--raw'

variants:
  - name: no-image
    notes: "Optionally add classes of <code>has-solid-bg</code> to <code>.header-site</code> and <code>.breadcrumbs</code> to give them solid back backgrounds, rather than semitransparent."